language: python

python:
    - "pypy"
    - "pypy3"
    - "2.6"
    - "2.7"
    - "2.7_with_system_site_packages"
    - "3.2"
    - "3.2_with_system_site_packages"
    - "3.3"
    - "3.4"

before_install:
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then travis_retry pip install unittest2; fi
    - travis_retry pip install coveralls
    - travis_retry pip install --quiet git+https://github.com/python-imaging/Pillow.git
    - travis_retry sudo apt-get --quiet=2 install perceptualdiff

    # we only have gdal in system packages
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7_with_system_site_packages" -o "$TRAVIS_PYTHON_VERSION" == "3.2_with_system_site_packages" ]; then pushd depends && ./install_gdal.sh && popd; fi

script:
    - coverage erase
    - coverage run --source heatmap --append ./test/test.py
    - coverage run --source heatmap --append ./test/test_coordinates.py
    - coverage run --source heatmap --append ./test/test_projections.py
    - coverage run --source heatmap --append ./test/test_gpx.py
    - coverage run --source heatmap --append ./test/test_projection_scale.py
    - coverage run --source heatmap --append ./test/test_random.py
    - coverage run --source heatmap --append ./test/test_gradients.py

    # we only have gdal in system packages
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7_with_system_site_packages" -o "$TRAVIS_PYTHON_VERSION" == "3.2_with_system_site_packages" ]; then coverage run --source heatmap --append ./test/test_shp_file.py; fi

after_success:
    - coverage report
    - coveralls
    - travis_retry pip install pep8 pyflakes
    - pep8 *.py
    - pyflakes *.py
    - pep8 test/*.py
    - pyflakes test/*.py
